# Generated by Django 5.1.5 on 2025-01-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salaries_for_cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_salary', models.FloatField()),
                ('city', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Salaries_for_cities',
                'db_table': 'Salaries_for_cities',
            },
        ),
        migrations.CreateModel(
            name='Top_skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.JSONField()),
                ('year', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Top_skills',
                'db_table': 'Top_skills',
            },
        ),
        migrations.CreateModel(
            name='Vacancies_for_cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_of_vacancies', models.FloatField()),
                ('city', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Vacancies_for_cities',
                'db_table': 'Vacancies_for_cities',
            },
        ),
        migrations.CreateModel(
            name='Vacancies_for_years',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancies_amount', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Vacancies_for_years',
                'db_table': 'Vacancies_for_years',
            },
        ),
    ]
