# Generated by Django 5.1.5 on 2025-01-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_salaries_for_cities_top_skills_vacancies_for_cities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cur_code', models.CharField(max_length=5)),
                ('currencies', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'db_table': 'Currencies',
                'unique_together': {('cur_code', 'date')},
            },
        ),
    ]
