# Generated by Django 5.1.5 on 2025-01-14 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_currencies'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vacancy',
            table='Vacancies',
        ),
    ]
